# See https://pre-commit.com/ for usage and config
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-toml
            stages:
                - commit
            types:
                - toml
          - id: check-xml
            stages:
                - commit
            types:
                - xml
          - id: check-yaml
            stages:
                - commit
            types:
                - yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            stages:
                - commit
            types:
                - python
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            stages:
                - commit
            types:
                - python
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            stages:
                - commit
            types:
                - python
            exclude: setup.py
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.991
      hooks:
          - id: mypy
            stages:
                - commit
            types:
                - python
            require_serial: true

    - repo: local
      hooks:
          - id: pytest
            name: pytest
            stages:
                - commit
            language: system
            entry: poetry run pytest
            types:
                - python
            pass_filenames: false

          - id: pytest-cov
            name: pytest
            stages:
                - push
            language: system
            entry: poetry run pytest --cov --cov-fail-under=80
            types:
                - python
            pass_filenames: false
    - repo: https://github.com/python-poetry/poetry
      rev: 1.2.2
      hooks:
          - id: poetry-check
          - id: poetry-lock
