---
# spell-checker: disable
# See https://pre-commit.com/ for usage and config
repos:
    - hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-toml
            stages:
                - pre-commit
            types:
                - toml
          - id: check-xml
            stages:
                - pre-commit
            types:
                - xml
          - id: check-yaml
            args:
                - --allow-multiple-documents
            stages:
                - pre-commit
            types:
                - yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.28.0
      hooks:
          - id: gitleaks
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.12.10
      hooks:
          - id: ruff-check
          - id: ruff-format
            args:
                - --check
    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.8.13
      hooks:
          - id: uv-lock
          # Run the pip compile
          #   - id: pip-compile
          #     args:
          #         - pyproject.toml
          #         - -o
          #         - requirements.txt
          #         - --all-extras
    - repo: https://github.com/opensource-nepal/commitlint
      rev: v1.3.1
      hooks:
          - id: commitlint
    # - repo: https://github.com/pypa/pip-audit
    #   rev: v2.8.0
    #   hooks:
    #       - id: pip-audit
    #         args:
    #             - .

ci:
    # Leave pip-audit to only run locally and not in CI
    # pre-commit.ci does not allow network calls
    skip:
        - pip-audit
