---
# spell-checker: disable
# See https://pre-commit.com/ for usage and config
repos:
    - hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-toml
            stages:
                - commit
            types:
                - toml
          - id: check-xml
            stages:
                - commit
            types:
                - xml
          - id: check-yaml
            args:
                - --allow-multiple-documents
            stages:
                - commit
            types:
                - yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.18.2
      hooks:
          - id: gitleaks
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.3.0
      hooks:
          - id: ruff
          - id: ruff-format
            args:
                - --check
    - hooks:
          - id: poetry-check
          - id: poetry-lock
      repo: https://github.com/python-poetry/poetry
      rev: 1.8.0
