---
# See https://pre-commit.com/ for usage and config
repos:
    - hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-toml
            stages:
                - commit
            types:
                - toml
          - id: check-xml
            stages:
                - commit
            types:
                - xml
          - id: check-yaml
            args:
                - --allow-multiple-documents
            stages:
                - commit
            types:
                - yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
    - repo: https://github.com/awslabs/git-secrets.git
      rev: 1.3.0
      hooks:
          - id: git-secrets
    - repo: https://github.com/timothycrosley/isort
      rev: 5.12.0
      hooks:
          - id: isort
    - hooks:
          - id: black
            stages:
                - commit
            types:
                - python
      repo: https://github.com/psf/black
      rev: 23.7.0
    - repo: https://github.com/flakeheaven/flakeheaven
      rev: 3.3.0
      hooks:
          - id: flakeheaven
            additional_dependencies:
                [
                    "flake8>=4.0.1,<5.0.0",
                    "flake8-builtins~=2.1.0",
                    "flake8-blind-except~=0.2.1",
                    "flake8-logging-format~=0.9.0",
                    "flake8-bugbear~=23.2.13",
                    "flake8-annotations~=2.9.1",
                    "flake8-docstrings~=1.7.0",
                    "flake8-bandit~=3.0.0",
                    "flake8-broken-line~=0.6.0",
                    "darglint~=1.8.1",
                ]

    - hooks:
          - entry: poetry run mypy
            id: mypy
            language: system
            name: mypy
            require_serial: true
            stages:
                - commit
            types:
                - python
          - entry: poetry run pytest
            id: pytest
            language: system
            name: pytest
            pass_filenames: false
            stages:
                - commit
            types:
                - python
          - entry: poetry run pytest --cov --cov-fail-under=80
            id: pytest-cov
            language: system
            name: pytest
            pass_filenames: false
            stages:
                - push
            types:
                - python
      repo: local
    - hooks:
          - id: poetry-check
          - id: poetry-lock
      repo: https://github.com/python-poetry/poetry
      rev: 1.5.0
