---
# spell-checker: disable
# See https://pre-commit.com/ for usage and config
repos:
    - hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-toml
            stages:
                - commit
            types:
                - toml
          - id: check-xml
            stages:
                - commit
            types:
                - xml
          - id: check-yaml
            args:
                - --allow-multiple-documents
            stages:
                - commit
            types:
                - yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.18.1
      hooks:
          - id: gitleaks
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.1.7
      hooks:
          - id: ruff
          - id: ruff-format
            args:
                - --check
    #       - entry: poetry run pytest
    #         id: pytest
    #         language: system
    #         name: pytest
    #         pass_filenames: false
    #         stages:
    #             - commit
    #         types:
    #             - python
    #       - entry: poetry run pytest --cov --cov-fail-under=80
    #         id: pytest-cov
    #         language: system
    #         name: pytest
    #         pass_filenames: false
    #         stages:
    #             - push
    #         types:
    #             - python
    #   repo: local
    - hooks:
          - id: poetry-check
          - id: poetry-lock
      repo: https://github.com/python-poetry/poetry
      rev: 1.7.0
