---
name: Publish docker image
on:
    push:
        tags:
            - "*"
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Publish to GitHub packages
              uses: whoan/docker-build-with-cache-action@v6
              with:
                  image_name: ${{ github.repository }}/adventofcode
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  username: ${{ github.actor }}
