---
name: Update Progress Image
on:
    schedule:
        - cron: "07 05 1-25 12 *" # 5:07 AM UTC, Dec 1-25
    workflow_dispatch: null
    workflow_run:
        types:
            - completed
        workflows:
            - Test
jobs:
    update-aoc-progress:
        if: >-
            ${{
                github.event_name != 'workflow_run' ||
                github.event.workflow_run.conclusion == 'success'
            }}
        runs-on: ubuntu-latest # renovate: runner

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Generate AoC progress
              run: python .github/generate_aoc_readme.py

            - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
              with:
                  commit_message: Update AoC progress
                  file_pattern: .github/aoc_progress.svg
